services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend-web
    networks:
      - internal

  post-service:
    image: post-service
    container_name: post-service
    depends_on:
      - post-service-db
      - auth-server
    restart: always
    volumes:
      - post_service_volume:/root
    networks:
      - internal
    expose:
      - "8080:8080"

  post-service-db:
    image: postgres:latest
    container_name: post-service-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: koinelab
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    expose:
      - "5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    expose:
      - "81:81"
    networks:
      - internal
    volumes:
      - pg-admin:/var/lib/pgadmin
    depends_on:
      - post-service-db

  frontend-web:
    image: koinelab-frontend-web:latest
    container_name: frontend-web
    depends_on:
      - post-service
      - auth-server
    networks:
      - internal
    expose:
      - "3000:3000"

  auth-server:
    image: quay.io/keycloak/keycloak:latest
    container_name: auth-server
    environment:
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=password
    - KC_HTTP_ENABLED=true
    - KC_PROXY=edge
    - KC_HOSTNAME_STRICT=false
    - KC_HOSTNAME_STRICT_HTTPS=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/auth/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start",
     "--http-port", "7080",
      "--proxy-headers", "xforwarded",
       "--hostname", "http://localhost/auth",
        "--hostname-strict", "false",
         "--hostname-backchannel-dynamic", "true"]
#    depends_on:
#      - auth-server-db
    expose:
      - "7080:7080"
      - "7443:7443"
    volumes:
      - auth-server:/opt/keycloak/data
    networks:
      - internal

#  auth-server-db:
#    image: postgres:latest
#    container_name: keycloak-db
#    environment:
#      - POSTGRES_DB=keycloak
#      - POSTGRES_USER=keycloak
#      - POSTGRES_PASSWORD=password
#    volumes:
#      - auth-server-db:/var/lib/postgresql/data


volumes:
  nginx:
  postgres_data:
  pg-admin:
  auth-server:
  auth-server-db:
  post_service_volume:

networks:
  internal:
    driver: bridge
